### ISSUE TITLE
Add Unicode 9 Emoji

### ISSUE THREAD

**Issue by connorshea** [jonathanwiesel/gemojione#10]
Emoji One 2.2.4 was released the other day with the Unicode 9 emoji! Can we get an update with them? 

http://emojione.com/releases/#2.2.4

**Comment by jonathanwiesel** [comment]
There are some known problems with the latest EmojiOne release, such as missing categories and incorrect shortnames, there should be a new version coming out in a few days, when that update comes I'll proceed and update the gem

**Comment by jonathanwiesel** [comment]
It seems EmojiOne v2.2.5 fixes categorizarion issues on unicode9.

Update pending.

**Comment by connorshea** [comment]
Looking forward to it! Ping me if you need any help or want someone to review the MR :)

**Comment by jonathanwiesel** [comment]
It seems that unicode9 emoji still present categorization issues on the original repo according to this Ranks/emojione#287
