### ISSUE TITLE
Categories for some emoji are incorrect

### ISSUE THREAD

**Issue by connorshea** [jonathanwiesel/gemojione#11]
For example, the banana emoji is an "object" when it should be in the category "foods". As is apple, bread, cake, candy, etc.

`index.json` for the latest commit: https://raw.githubusercontent.com/jonathanwiesel/gemojione/b922391b0a85cb6c35483eabbfeecb399246385c/config/index.json

**Comment by connorshea** [comment]
You can see this in the emoji picker on GitLab, e.g. https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/4919

<img width="287" alt="screen shot 2016-06-25 at 5 49 02 pm" src="https://cloud.githubusercontent.com/assets/2977353/16359717/2587381e-3afd-11e6-81bf-384e624d6a23.png">

**Comment by connorshea** [comment]
Some others: tomato, orange, peach, strawberry, pear, melon, lemon, green apple, grapes, burger, ice cream, corn, cherries, beer, fries, shrimp, meat_on_bone, donut, curry, custard, eggplant.

**Comment by jonathanwiesel** [comment]
You're right, I'll re-match the categories from the original emojione definitions in the next few days
