### ISSUE TITLE
`replace_named_moji_with_images` doesn't work with aliases

### ISSUE THREAD

**Issue by nmdoliveira** [jonathanwiesel/gemojione#36]
I'm not sure if this is intended, but I was expecting that `replace_named_moji_with_images` would work with aliases too. My specific case is `:robot_face:`: its actual name is `:robot:` and `:robot_face:` is an alias. But when I call `Gemojione.replace_named_moji_with_images(":robot_face:")`, it returns `":robot_face:"`.

Looking at the source, I suppose it's because the regex used in this method (`shortname_moji_regex`) is generated from the Index's `@emoji_by_code`, and aliases are added to `@emoji_by_name`. Would it be acceptable if aliases were added to `@emoji_by_code` too? If so, I could make a pull request for that. 

Thanks in advance :smile:

**Comment by jonathanwiesel** [comment]
This would be a good enhancement to add for the gem. Will add it to the backlog. Thanks @nmdoliveira
