### ISSUE TITLE
"desert" keyword is returning emoji for the "dessert"

### ISSUE THREAD

**Issue by wperoche429** [jonathanwiesel/gemojione#37]
"desert" keyword is returning emoji for the "dessert"

**Comment by jonathanwiesel** [comment]
Hi @wperoche429, you're right, it seems many changes have been implemented for the keywords array in the source repo (Ranks/emojione). When 3.0 is released we should take this into consideration when updating this gem.

**Comment by amclelland** [comment]
Looks like this is fixed now 👍
