### ISSUE TITLE
Add emoji retrieval via shortname

### ISSUE THREAD

**Issue by amyspark** [jonathanwiesel/gemojione#41]
At the moment, gemojione provides a regex for matching all possible emoji short names. However, there is not a `find_by_shortname` method in the index. Could this be added?

I can file a pull request if asked, I've done it locally.

**Comment by jonathanwiesel** [comment]
Sorry for the delay.

Indeed a `find_by_shortname` method could be added by checking the `emoji_by_code` hash.

Feel free to file the pull request.

Thank you @amyspark
