### ISSUE TITLE
Possibility to downcase emoji codes when generating urls?

### ISSUE THREAD

**Issue by nmdoliveira** [jonathanwiesel/gemojione#45]
Some CDNs name the emoji image files with the downcased version of the emoji code, for example "1f61b" instead of "1F61B". [Cloudflare](https://cdnjs.com/libraries/emojione) is an example.

Even jsdelivr, which I was using, is failing for some uppercase codes, but working for the downcase version. Example: I get this url for `:clown:`: https://cdn.jsdelivr.net/emojione/assets/svg/1F921.svg, which gives me an "Access Denied" error, but the downcase version works normally: https://cdn.jsdelivr.net/emojione/assets/svg/1f921.svg.

Is this a problem with the CDNs or would it make sense to be able to downcase the codes in this gem?

**Comment by jonathanwiesel** [comment]
Since you're getting the images from a CDN and not the gem itself this would not be a gem issue, the gem's image names are stored uppercase form so it wouldn't be an issue with the own gem images.

**Comment by nmdoliveira** [comment]
Thanks for your response! I ended up making a fork, but it seems it was an issue with the CDN (https://github.com/Ranks/emojione/issues/463) that should be resolved now.
