### ISSUE TITLE
Support for Emojione v3.x.x

### ISSUE THREAD

**Issue by MerlinMason** [jonathanwiesel/gemojione#53]
Hi there,

Thanks for an awesome product.
Just wondering if there's plans to update to the latest version of Emojione / Unicode 10?

Thanks!

**Comment by connorshea** [comment]
Here's last year's PR to update to Unicode 9. https://github.com/jonathanwiesel/gemojione/pull/18

The problem is that there were breaking changes in Emojione 3.0.0, so it may not be as easy to update the gem this time :(

**Comment by amclelland** [comment]
Updated to EmojiOne v4.5 - please report any bugs you find!
