### ISSUE TITLE
Missing Emojis in index.json (Version 4.5.0)

### ISSUE THREAD

**Issue by kendrikat** [jonathanwiesel/gemojione#60]
Hey, 

just saw that quite a lot emojis are missing in the `index.json` file. (Seems 162 are missing, unless I'm totally wrong. I compared with [this file](https://github.com/joypixels/emojione/blob/4.5.0/emoji.json))

A few examples:
- `zany_face`
- `hot_face`
- `cold_face` 

Is there a way to generate these, or do we have to add each emoji manually?

**Comment by amclelland** [comment]
I believe all the missing emojis have been added on [this branch](https://github.com/bonusly/gemojione/compare/update-mojis?expand=1), but it's been a while since I started that. I'll try to get this cleaned up this week!
